# NUMPY TUTORIAL

In [1]:
import numpy as np

In [18]:
myarr=np.array([5,4,3,2,1])

In [19]:
print(myarr)

[5 4 3 2 1]


In [12]:
myarr[0]

3

In [13]:
myarr.dtype

dtype('int64')

In [14]:
myarr.shape

(4,)

In [20]:
zeros=np.zeros((2,5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
rng=np.arange(15)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
lspace=np.linspace(1,10,10)

In [30]:
lspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
emp=np.empty((4,6))

In [32]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        8.90100844e-307, 1.69109959e-306, 1.29062025e-306],
       [1.33511018e-306, 1.33511969e-306, 6.23037996e-307,
        6.23053954e-307, 9.34609790e-307, 8.45593934e-307],
       [9.34600963e-307, 1.86921143e-306, 6.23061763e-307,
        8.90104239e-307, 6.89804132e-307, 1.22387465e-307],
       [1.42418172e-306, 2.04712906e-306, 7.56589622e-307,
        1.11258277e-307, 8.90111708e-307, 2.56765117e-312]])

In [34]:
empl=np.empty_like(lspace)

In [35]:
empl

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
ide=np.identity(45)

In [37]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [58]:
arr=np.arange(99)

In [59]:
type(arr)

numpy.ndarray

In [60]:

arr=arr.reshape(3,33)

In [61]:
type(arr)

numpy.ndarray

In [62]:
type(arr)

numpy.ndarray

In [64]:
arr.shape

(3, 33)

In [65]:
type(arr)

numpy.ndarray

In [66]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [67]:
arr.shape

(3, 33)

In [68]:
arr=arr.ravel()

In [69]:
arr.shape

(99,)

In [70]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [71]:
arr=np.array(x)

In [72]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [73]:
arr.sum(axis=0)

array([12,  8,  9])

In [74]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [75]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [77]:
arr.flat

In [78]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [79]:
arr.nbytes

36

In [80]:
one=np.array([3,45,67,89,23])

In [81]:
one.argmax()

3

In [82]:
one.argmin()

0

In [83]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [84]:
arr.argmin()

8

In [85]:
arr.argmax()

6

In [86]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [87]:
arr.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [89]:
 arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [90]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [91]:
arr.reshape(9,-1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [93]:
arr.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 1, 0]])

In [95]:
one.sum(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [96]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [98]:
ar=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [99]:
ar+arr

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [100]:
 [324,34]+[34,546]

[324, 34, 34, 546]

In [101]:
arr*ar

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [102]:
arr//ar

C:\Users\Nidhi Sharma\AppData\Local\Temp\ipykernel_3960\2291225477.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  arr//ar


array([[1, 1, 3],
       [1, 0, 1],
       [0, 1, 0]])

In [103]:
arr/ar

C:\Users\Nidhi Sharma\AppData\Local\Temp\ipykernel_3960\3952804342.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/ar
C:\Users\Nidhi Sharma\AppData\Local\Temp\ipykernel_3960\3952804342.py:1: RuntimeWarning: invalid value encountered in divide
  arr/ar


array([[1.   , 1.   , 3.   ],
       [1.   ,   inf, 1.   ],
       [0.875, 1.   ,   nan]])

In [105]:

np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [106]:
arr.max()

7

In [107]:
arr.sum()

29

In [109]:
type(np.where(arr>5))

tuple

In [110]:
ar

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [111]:
np.count_nonzero(ar)

7

In [112]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1], dtype=int64))

In [ ]:
# pandas tutorial